[versions]
agp = "7.4.2"
crashreportVersion = "latest.release"
datastorePreferencesVersion = "1.1.1"
kotlin = "1.8.10"
coreKtx = "1.10.1"
junitVersion = "5.7.0"
androidXJunitVersion = "1.1.3-alpha03"
assertjVersion = "3.19.0"
coreTestingVersion = "2.1.0"
espressoIntentsVersion = "3.3.0"
espressoVersion = "3.3.0"
coroutinesTestVersion = "1.4.2-native-mt"
appcompatVersion = "1.6.1"
materialVersion = "1.10.0"
activityKtxVersion = "1.8.2"
pagingRuntimeKtxVersion = "3.2.1"
retrofitVersion = "2.9.0"
moshiVersion = "1.15.1"
okhttpInterceptorVersion = "4.9.0"
mockVersion = "1.10.5"
annotationVersion = "1.1.0"
glideVersion = "4.11.0"
hilt_version = "2.46"
picassoVersion = "2.71828"
lifecycle_version = "2.6.1"  #livedata和viewmodel使用相同版本
espressoIdlingResourceVersion = "3.7.0"
navigationFragmentVersion = "2.8.0"
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCoreVersion = "3.5.1"
tensorflowLiteVersion = "2.15.0"
swiperefreshlayoutVersion = "1.1.0"
orgEclipsePahoClientMqttv3Version = "1.2.5"


[libraries]
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesVersion" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtxVersion" }
crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreportVersion" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotationVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtxVersion" }

lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle_version" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }

retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofitVersion" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiVersion" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiVersion" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpInterceptorVersion" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glideVersion" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picassoVersion" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt_version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt_version" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt_version" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt_version" }


junit = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidXJunitVersion" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoIntentsVersion" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espressoVersion" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoVersion" }
arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTestingVersion" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTestVersion" }
androidx-espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espressoIdlingResourceVersion" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragmentVersion" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationFragmentVersion" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLiteVersion" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }

org-eclipse-paho-client-mqttv3 = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "orgEclipsePahoClientMqttv3Version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
android-library = { id = "com.android.library", version.ref = "agp" }
